### ISSUE TITLE
BillingClient crash

### ISSUE THREAD

**Issue by budajov** [exponea/exponea-android-sdk#11]
Hi,

I have a problem with exponea sdk. I integrated version 1.1.7 and when i try to initialize sdk, app goes crashing and i get this message:

**E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scratchy.app.inc, PID: 23900
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
        at java.util.ArrayList.<init>(ArrayList.java:191)
        at com.android.billingclient.api.SkuDetailsParams$Builder.build(SkuDetailsParams.java:72)
        at com.exponea.sdk.manager.IapManagerImpl.getAvailableProducts(IapManagerImpl.kt:77)
        at com.exponea.sdk.manager.IapManagerImpl$configure$1.onBillingSetupFinished(IapManagerImpl.kt:33)
        at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected(BillingClientImpl.java:1030)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1652)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1681)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)**

Could you help me please?

**Comment by nickskull** [comment]
Hi @budajov, thank you for your patience. We've now been able to resolve this crash and update the billing client dependency. However, due to the nature of these changes it is now required to pass on an SKU list of the in app purchases you wish to track to Exponea SDK. 

You can read [more about this here](https://github.com/exponea/exponea-android-sdk/blob/2.2.0/Documentation/RELEASE_NOTES.md).
