### ISSUE TITLE
App crash: Infinity is not a valid double value as per JSON specification. method. com.exponea.sdk.network.ExponeaServiceImpl.doPost

### ISSUE THREAD

**Issue by kochchy** [exponea/exponea-android-sdk#20]
hello, app started crashing on this:
`Fatal Exception: java.lang.IllegalArgumentException: Infinity is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.
       at com.google.gson.Gson.checkValidFloatingPoint(Gson.java:359)
       at com.google.gson.Gson$1.write(Gson.java:327)
       at com.google.gson.Gson$1.write(Gson.java:313)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
       at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
       at com.google.gson.Gson.toJson(Gson.java:704)
       at com.google.gson.Gson.toJson(Gson.java:683)
       at com.google.gson.Gson.toJson(Gson.java:638)
       at com.google.gson.Gson.toJson(Gson.java:618)
       at com.exponea.sdk.network.ExponeaServiceImpl.doPost(ExponeaServiceImpl.kt:58)
       at com.exponea.sdk.network.ExponeaServiceImpl.postEvent(ExponeaServiceImpl.kt:21)
       at com.exponea.sdk.manager.FlushManagerImpl.routeSendingEvent(FlushManagerImpl.kt:120)
       at com.exponea.sdk.manager.FlushManagerImpl.trySendingEvent(FlushManagerImpl.kt:63)
       at com.exponea.sdk.manager.FlushManagerImpl.flushDataInternal(FlushManagerImpl.kt:49)
       at com.exponea.sdk.manager.FlushManagerImpl.access$flushDataInternal(FlushManagerImpl.kt:16)
       at com.exponea.sdk.manager.FlushManagerImpl$handleResponse$1.invoke(FlushManagerImpl.kt:113)
       at com.exponea.sdk.manager.FlushManagerImpl$handleResponse$1.invoke(FlushManagerImpl.kt:16)
       at com.exponea.sdk.util.ExtensionsKt$enqueue$1.onResponse(Extensions.kt:29)
       at com.google.firebase.perf.network.zzf.onResponse(com.google.firebase:firebase-perf@@19.0.3:22)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by Igi4** [comment]
@kochchy Hi, thanks for the report, we'll take a look at it. Could you please tell me what version of the SDK are you using? Thank you.

**Comment by kochchy** [comment]
@Igi4 version 2.6.0

**Comment by wassil** [comment]
Hi @kochchy,
issue has been fixed in latest release(2.6.2). Positive/negative infinity and NaN values are now serialized as string and sent to Exponea servers.
Please note that Exponea doesn't support such values for numbers, so although the app won't crash, you should not send those values in events.
