### ISSUE TITLE
App crash: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String com.exponea.sdk.models.InAppMessagePayload.getImageUrl()' on a null object reference com.exponea.sdk.manager.InAppMessageManagerImpl.hasImageFor

### ISSUE THREAD

**Issue by nkartyshov** [exponea/exponea-android-sdk#33]
Hello, Android app crashes, when using Exponea SDK:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.exponea.sdk.models.InAppMessagePayload.getImageUrl()' on a null object reference
       at com.exponea.sdk.manager.InAppMessageManagerImpl.hasImageFor(InAppMessageManagerImpl.java:4)
       at com.exponea.sdk.manager.InAppMessageManagerImpl.getFilteredMessages(InAppMessageManagerImpl.java:124)
       at com.exponea.sdk.manager.InAppMessageManagerImpl.getRandom(InAppMessageManagerImpl.java:10)
       at com.exponea.sdk.manager.InAppMessageManager$DefaultImpls.getRandom$default(InAppMessageManager.java:7)
       at com.exponea.sdk.manager.InAppMessageManagerImpl$showRandom$1.invokeSuspend(InAppMessageManagerImpl.java:31)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:9)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:93)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)
```

Exponea SDK versions: v2.7.4 and v2.9.0
Android versions: 11, 10, 9, 8

**Comment by wassil** [comment]
Hi,
are you using AB testing for in-app messages by any chance?
There is an open issue with AB testing for in-app messages. Control group of AB tests has `null` payload and results in this crash.
My advice is to disable AB testing or set it up so that there is 0% in the control group.

**Comment by nkartyshov** [comment]
Hi. Yes, we were used A/b testing. We were using control group 50% user showed in-app messages  and 50% not showed.
