### ISSUE TITLE
InAppMessageShowRequest.getRequestedAt() null pointer

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#40]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long com.exponea.sdk.manager.InAppMessageShowRequest.getRequestedAt()' on a null object reference
       at com.exponea.sdk.manager.InAppMessageManagerImpl.pickPendingMessage(InAppMessageManagerImpl.java:169)
       at com.exponea.sdk.manager.InAppMessageManagerImpl.showPendingMessage(InAppMessageManagerImpl.java:183)
       at com.exponea.sdk.manager.InAppMessageManagerImpl.showPendingMessage$default(InAppMessageManagerImpl.java:182)
       at com.exponea.sdk.manager.InAppMessageManagerImpl$preload$2.invoke(InAppMessageManagerImpl.java:78)
       at com.exponea.sdk.manager.InAppMessageManagerImpl$preload$2.invoke(InAppMessageManagerImpl.java:38)
       at com.exponea.sdk.manager.FetchManagerImpl$getFetchCallback$1.onResponse(FetchManagerImpl.java:53)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

sdk 2.9.4, 
Device
Brand:Xiaomi
Model:Redmi Note 7
Orientation: Portrait
RAM free: 1.05 GB
Disk free: 17.54 GB
Operating System
Version:10
Orientation: Portrait
Rooted:No

**Comment by ursusursus** [comment]
Pozrie sa na toto niekto? Crashuje to obe appky

**Comment by adam1929** [comment]
Hi @ursusursus, sorry for late answer. This problem has been removed meanwhile, please consider to use latest 3.1.0 version; SDK api should never re-throw any exception now.
