### ISSUE TITLE
Tracking on main thread

### ISSUE THREAD

**Issue by ursusursus** [exponea/exponea-android-sdk#46]
Zdravim,
I noticed strictmode complains about SQL inserts on main thread

```
2022-02-01 00:03:55.684 14685-14685/sk.o2.radost.mock D/StrictMode: StrictMode policy violation; ~duration=20 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1615)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1201)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:937)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at com.exponea.sdk.database.ExportedEventDao_Impl.add(ExportedEventDao_Impl.java:202)
        at com.exponea.sdk.database.ExponeaDatabase.add(ExponeaDatabase.kt:21)
        at com.exponea.sdk.repository.EventRepositoryImpl.add(EventRepositoryImpl.kt:36)
        at com.exponea.sdk.manager.EventManagerImpl.addEventToQueue(EventManagerImpl.kt:51)
        at com.exponea.sdk.manager.EventManagerImpl.track(EventManagerImpl.kt:77)
        at com.exponea.sdk.Exponea$trackEvent$1$1.invoke(Exponea.kt:334)
        at com.exponea.sdk.Exponea$trackEvent$1$1.invoke(Exponea.kt:333)
        at com.exponea.sdk.Exponea.requireInitialized$sdk_release(Exponea.kt:598)
        at com.exponea.sdk.Exponea.requireInitialized(Exponea.kt:603)
        at com.exponea.sdk.Exponea.requireInitialized$default(Exponea.kt:602)
        at com.exponea.sdk.Exponea.trackEvent(Exponea.kt:333)
        at sk.o2.analytics.exponea.tracker.ExponeaAnalyticsTracker.trackEvent(ExponeaAnalyticsTracker.kt:78)
        at sk.o2.analytics.exponea.tracker.ExponeaAnalyticsTracker.trackScreenView(ExponeaAnalyticsTracker.kt:64)
        at sk.o2.analytics.Analytics.trackScreenView(Analytics.kt:18)
        at sk.o2.conductor.ViewBindingController.onViewCreated(ViewBindingController.kt:51)
        at sk.o2.conductor.ViewBindingController.onCreateView(ViewBindingController.kt:42)
        at sk.o2.conductor.BaseController.onCreateView(BaseController.kt:42)

```

Which happens for example when we track screen views, which is not great.

Should I move the Exponea.trackEvent to IO thread, or will the library implement this eventually?
I could just post it to IO dispatcher in coroutines, but then I'd risk getting stuff out of order, so probably a queue is necessary, which I think should be the library responsibility

**Comment by michaela-dev** [comment]
Hi, there are plans to solve this directly in the SDK, should be the library's responsibility. It's not scheduled for any particular release yet, but we understand it is technical debt and we will try to solve this ASAP. Thanks for the report btw.

**Comment by adam1929** [comment]
Hi @ursusursus  we added this issue into our plans. We are going to change internal architecture to fully support app API as Async processes, but it leads to major changes.
For your case, please try to use SDK in background thread yourself for now. Thank you
