### ISSUE TITLE
FetchManagerImpl.fetchInAppMessages - NullPointerException - Parameter specified as non-null is null

### ISSUE THREAD

**Issue by viktor-savchik-idf** [exponea/exponea-android-sdk#57]
After update from 3.2.1 to 3.4.0 version face with the following crash

```Kotlin
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method com.exponea.sdk.manager.FetchManagerImpl$fetchInAppMessages$2.invoke, parameter result
       at com.exponea.sdk.manager.FetchManagerImpl$fetchInAppMessages$2.invoke(FetchManagerImpl.kt:160)
       at com.exponea.sdk.manager.FetchManagerImpl$fetchInAppMessages$2.invoke(FetchManagerImpl.kt:157)
       at com.exponea.sdk.manager.FetchManagerImpl$getFetchCallback$1.onResponse(FetchManagerImpl.kt:48)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:933)
```

**Comment by adam1929** [comment]
@viktor-savchik-idf Thank you for your report.
We already checked this issue and we are not able to reproduce it (event if problem is obvious, response data are null).
Can you please report this issue with HTTP logs to support? Really thanks, it will help us to fully understand an origin of problem. Thank you

**Comment by viktor-savchik-idf** [comment]
@adam1929 I wish I could we can reproduce it to provide HTTP logs but we can't. However a lot of our users are facing with it. So for now we rolled back to the v3.2.1. We will try to reproduce again, If we can reproduce it, we will provide HTTP logs

**Comment by xcibik00** [comment]
Hi @viktor-savchik-idf , in version 3.5.0 we just released the additional check was added for invalid (empty) response that we think could cause this. Please let us know if it helps. In other case also HTTP logs will be necessary.
