### ISSUE TITLE
Remove DB calls on Main Thread

### ISSUE THREAD

**Issue by sergei-mikhailovskii-idf** [exponea/exponea-android-sdk#71]
Hi, we enabled a strict mode in the application and found out some cases that cannot be handled from our side - SDK executes api call on the Main Thread. Here's the log

```
StrictMode policy violation; ~duration=50 ms: android.os.strictmode.DiskWriteViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1635)
                                                                                                    	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1304)
                                                                                                    	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:740)
                                                                                                    	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:336)
                                                                                                    	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:311)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:814)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:797)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:653)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransaction(FrameworkSQLiteDatabase.java:69)
                                                                                                    	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:354)
                                                                                                    	at com.exponea.sdk.database.ExportedEventDao_Impl.add(ExportedEventDao_Impl.java:200)
                                                                                                    	at com.exponea.sdk.database.ExponeaDatabase.add(ExponeaDatabase.kt:21)
                                                                                                    	at com.exponea.sdk.repository.EventRepositoryImpl.add(EventRepositoryImpl.kt:36)
                                                                                                    	at com.exponea.sdk.manager.EventManagerImpl.addEventToQueue(EventManagerImpl.kt:49)
                                                                                                    	at com.exponea.sdk.manager.EventManagerImpl.processTrack(EventManagerImpl.kt:97)
                                                                                                    	at com.exponea.sdk.manager.EventManagerImpl.track(EventManagerImpl.kt:69)
                                                                                                    	at com.exponea.sdk.manager.EventManager$DefaultImpls.track$default(EventManager.kt:7)
                                                                                                    	at com.exponea.sdk.manager.SessionManagerImpl.trackSessionStart(SessionManagerImpl.kt:130)
                                                                                                    	at com.exponea.sdk.manager.SessionManagerImpl.onSessionStart(SessionManagerImpl.kt:87)
                                                                                                    	at com.exponea.sdk.manager.SessionManager.onActivityResumed(SessionManager.kt:33)
                                                                                                    	at android.app.Application.dispatchActivityResumed(Application.java:431)
                                                                                                    	at android.app.Activity.dispatchActivityResumed(Activity.java:1590)
                                                                                                    	at android.app.Activity.onResume(Activity.java:2172)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:309)
                                                                                                    	at mx.card.plazo.android.base.BaseActivity.onResume(BaseActivity.kt:77)
                                                                                                    	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1722)
                                                                                                    	at android.app.Activity.performResume(Activity.java:9138)
                                                                                                    	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5257)
                                                                                                    	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5300)
                                                                                                    	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2608)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8628)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

can u please fix it? yes, I see that the duration is not too long but at the same time there are a lot of devices with low performance that are affected by it

**Comment by adam1929** [comment]
Thank you @sergei-mikhailovskii-idf for reporting it. We check it.

**Comment by sergei-mikhailovskii-idf** [comment]
Hi @adam1929! any news here? or is there any estimated date when u can give some response according to the issue? Thanks!

**Comment by adam1929** [comment]
Hi @sergei-mikhailovskii-idf we are working on solution. Please ask support for more detailed informations. Thank you
